#!/usr/bin/env python3
"""Bake tools/platform-tables.txt into a C++ include for the runtime.

The platform assist applies a per-level set of floor cells (pits filled so the
level needs no horizontal jumps). level_platforms.py emits the human-editable
"LEVEL N: room:idx[:val],..." table; this turns it into a compact lookup the
engine indexes by the live level number (state+8586). Regenerate after editing
the table:

  python3 tools/gen_platform_tables.py

Writes pop2-runtime/src/platform_tables.inc (room, idx, val per cell; default
val = 1 = floor). idx = row*10 + col, matching POP2_PLATFORMS.
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, 'platform-tables.txt')
OUT = os.path.join(HERE, '..', 'pop2-runtime', 'src', 'platform_tables.inc')

MAXLVL = 14


def parse():
    tables = {}  # level -> list of (room, idx, val)
    for line in open(SRC):
        m = re.match(r'\s*LEVEL\s+(\d+)\s*:\s*(.*)', line)
        if not m:
            continue
        lvl = int(m.group(1))
        cells = []
        for tok in m.group(2).split(','):
            tok = tok.strip()
            if not tok:
                continue
            parts = tok.split(':')
            room, idx = int(parts[0]), int(parts[1])
            val = int(parts[2]) if len(parts) > 2 else 1
            cells.append((room, idx, val))
        tables[lvl] = cells
    return tables


def main():
    tables = parse()
    out = []
    out.append('// Generated by tools/gen_platform_tables.py from '
               'tools/platform-tables.txt.')
    out.append('// Do not edit by hand -- edit the table and regenerate.')
    out.append('// Platform-assist floor fills, indexed by level (1..%d). '
               'idx = row*10 + col.' % MAXLVL)
    out.append('struct PlatCell { uint8_t room; uint8_t idx; uint8_t val; };')
    out.append('')
    for lvl in range(1, MAXLVL + 1):
        cells = tables.get(lvl, [])
        if not cells:
            continue
        body = ','.join('{%d,%d,%d}' % c for c in cells)
        out.append('static const PlatCell kPlatL%d[] = {%s};' % (lvl, body))
    out.append('')
    out.append('static const struct { const PlatCell* cells; int n; } '
               'kPlatTables[%d] = {' % (MAXLVL + 1))
    for lvl in range(0, MAXLVL + 1):
        if lvl >= 1 and tables.get(lvl):
            out.append('  {kPlatL%d, %d},' % (lvl, len(tables[lvl])))
        else:
            out.append('  {nullptr, 0},  // level %d' % lvl)
    out.append('};')
    out.append('')
    text = '\n'.join(out)
    open(OUT, 'w').write(text)
    total = sum(len(v) for v in tables.values())
    print('wrote %s: %d levels, %d cells'
          % (os.path.normpath(OUT), len([v for v in tables.values() if v]),
             total))


if __name__ == '__main__':
    main()
