#!/usr/bin/env python3
"""Convert a Linux console PSF font (psf1/psf2, optionally .gz) into a C array
of glyph bitmaps for ASCII 32..126, one byte per row, MSB = leftmost pixel.

Usage: psf2inc.py /usr/lib/kbd/consolefonts/default8x16.psfu.gz out.inc
"""
import gzip
import struct
import sys


def load(path):
    data = open(path, 'rb').read()
    if data[:2] == b'\x1f\x8b':
        data = gzip.decompress(data)
    if data[:2] == b'\x36\x04':  # PSF1
        mode, charsize = data[2], data[3]
        count = 512 if mode & 1 else 256
        width, height, off = 8, charsize, 4
        has_table = bool(mode & 2)
        glyphs = [data[off + i * charsize:off + (i + 1) * charsize]
                  for i in range(count)]
        table = data[off + count * charsize:] if has_table else b''
        uni = parse_table1(table, count) if has_table else None
        return glyphs, width, height, uni
    if data[:4] == b'\x72\xb5\x4a\x86':  # PSF2
        (_, hdrsize, flags, count, charsize, height,
         width) = struct.unpack('<6II', data[4:32])
        glyphs = [data[hdrsize + i * charsize:hdrsize + (i + 1) * charsize]
                  for i in range(count)]
        table = data[hdrsize + count * charsize:] if flags & 1 else b''
        uni = parse_table2(table, count) if flags & 1 else None
        return glyphs, width, height, uni
    sys.exit('not a PSF font')


def parse_table1(table, count):
    uni, pos = {}, 0
    for g in range(count):
        while pos + 1 < len(table):
            v = struct.unpack('<H', table[pos:pos + 2])[0]
            pos += 2
            if v == 0xFFFF:
                break
            if v != 0xFFFE:
                uni.setdefault(v, g)
    return uni


def parse_table2(table, count):
    uni, pos = {}, 0
    for g in range(count):
        while pos < len(table) and table[pos] != 0xFF:
            cp = table[pos]
            if cp < 0x80:
                pos += 1
            elif cp >= 0xF0:
                cp = ((cp & 7) << 18 | (table[pos + 1] & 0x3F) << 12 |
                      (table[pos + 2] & 0x3F) << 6 | (table[pos + 3] & 0x3F))
                pos += 4
            elif cp >= 0xE0:
                cp = ((cp & 0xF) << 12 | (table[pos + 1] & 0x3F) << 6 |
                      (table[pos + 2] & 0x3F))
                pos += 3
            else:
                cp = (cp & 0x1F) << 6 | (table[pos + 1] & 0x3F)
                pos += 2
            uni.setdefault(cp, g)
        pos += 1  # 0xFF terminator (skip 0xFE sequence parts the same way)
    return uni


def main():
    src, dst = sys.argv[1], sys.argv[2]
    glyphs, width, height, uni = load(src)
    if width != 8:
        sys.exit(f'expected 8px wide font, got {width}')
    out = [f'// Generated by tools/psf2inc.py from {src.split("/")[-1]}',
           f'// 95 glyphs (ASCII 32..126), {width}x{height}, MSB-left.',
           f'static const int kFontHeight = {height};',
           'static const unsigned char kFont[95][%d] = {' % height]
    for code in range(32, 127):
        g = uni.get(code, 0) if uni else code
        rows = ', '.join(f'0x{b:02X}' for b in glyphs[g][:height])
        out.append(f'    {{{rows}}},  // {chr(code)!r}')
    out.append('};')
    open(dst, 'w').write('\n'.join(out) + '\n')
    print(f'{dst}: {height}px, {len(glyphs)} glyphs in source')


if __name__ == '__main__':
    main()
